export const TEACHER_LOGIN_REQUEST = "TEACHER_LOGIN_REQUEST";
export const TEACHER_LOGIN_SUCCESS = "TEACHER_LOGIN_SUCCESS";
export const TEACHER_LOGIN_FAIL = "TEACHER_LOGIN_FAIL";
export const TEACHER_LOGOUT = "TEACHER_LOGOUT";

export const TEACHER_DETAILS_REQUEST = "TEACHER_LOGIN_REQUEST";
export const TEACHER_DETAILS_SUCCESS = "TEACHER_LOGIN_SUCCESS";
export const TEACHER_DETAILS_FAIL = "TEACHER_LOGIN_FAIL";

export const TEACHER_UPDATE_REQUEST = "TEACHER_UPDATE_REQUEST";
export const TEACHER_UPDATE_SUCCESS = "TEACHER_UPDATE_SUCCESS";
export const TEACHER_UPDATE_FAIL = "TEACHER_UPDATE_FAIL";
